CREATE TABLE IF NOT EXISTS memories(id BIGSERIAL PRIMARY KEY,content TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS reminders(id BIGSERIAL PRIMARY KEY,title TEXT NOT NULL,remind_at TIMESTAMP NOT NULL,completed BOOLEAN DEFAULT FALSE);
CREATE TABLE IF NOT EXISTS jobs(id BIGSERIAL PRIMARY KEY,company TEXT,title TEXT,url TEXT,match_score DOUBLE PRECISION,status TEXT DEFAULT 'DISCOVERED',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
